### PR TITLE
reduce network time spent on token swap

### PR DESCRIPTION
**Pull request by BlazeWasHere**
- Uses `Promise.all` to reduce time spent waiting
- Allows for user defined `swapData` to prevent `swapSetup` being called twice when calling both `calculateSwapRate` & `buildSwapTokensTransaction`

With `swapData` (after PR):
```js
import { Tokens, TokenSwap } from "./dist/index.js";

const amountIn = "420000000000000000000";
const tokenFrom = Tokens.USDC;
const tokenTo = Tokens.USDT;
const chainId = 1;

const swapData = await TokenSwap.swapSetup(tokenFrom, tokenTo, chainId);

const args = {
  chainId,
  tokenFrom,
  tokenTo,
  amountIn,
  swapData,
};
 
const { amountOut: minAmountOut } = await TokenSwap.calculateSwapRate(args);
const tx = await TokenSwap.buildSwapTokensTransaction({
  minAmountOut,
  ...args,
});
```
Without `swapData` (before PR):
```js
import { Tokens, TokenSwap } from "./dist/index.js";

const amountIn = "420000000000000000000";
const tokenFrom = Tokens.USDC;
const tokenTo = Tokens.USDT;
const chainId = 1;

const args = {
  chainId,
  tokenFrom,
  tokenTo,
  amountIn,
};
 
const { amountOut: minAmountOut } = await TokenSwap.calculateSwapRate(args);
const tx = await TokenSwap.buildSwapTokensTransaction({
  minAmountOut,
  ...args,
});
```

Currently a ~38% decrease in time spent.

```sh
$ time node before.js
5.690 total
$ time node after.js
3.546 total
```

### CODE REVIEW

**Comment by bleaker0x** [comment]
Interesting; @BlazeWasHere make sure tests pass and then I'll take a closer look at it. I like the idea and will probably end up merging it assuming tests are good to go.

**Comment by BlazeWasHere** [comment]
> Interesting; @BlazeWasHere make sure tests pass and then I'll take a closer look at it. I like the idea and will probably end up merging it assuming tests are good to go.

the tests pass, matic rpc node was down during the CI. Feel free to test it locally.

**Comment by bleaker0x** [comment]
@BlazeWasHere ah okey. Just rebase onto current dev (it's a squash commit so shouldn't be too painful on your end)

**Comment by BlazeWasHere** [comment]
> @BlazeWasHere ah okey. Just rebase onto current dev; ~(it's a squash commit so shouldn't be too painful on your end)~ disregard that, `dev` has quite a few more commits and changes now.
> 
> You might be better off nuking your local branch, pulling `dev`, and then making your changes again. Soz :P

Please do not force push branches, the PR had no conflicts originally. Will re-open the PR later on.

**Pull request closed without merging**
